// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fnkjxnltxopuljxyoxzx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZua2p4bmx0eG9wdWxqeHlveHp4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ5ODM2MjMsImV4cCI6MjA2MDU1OTYyM30.VAZEn1_H9VjI7GGfhfo6jUc-u-IZdsQ1yQHXC87gsb0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);